data = [{DistName:'North Sikkim',name:'MANGAN',discription:"Tourist places, Sightseeing Attractions and also to visit so many hills with full of ice",distance:"63 km",imgPath:'mangan.jpg',shopping:'Souvenirs from Sikkim,Carpets,Thankas, Choktses,Jewellery, Large Cardamom or Bari Elaichi',nearBy:'Aritar Lake,Baba Harbhajan Singh Memorial Temple,Bakthang Waterfalls,Ban Jhakri Falls ',toGo:'Bus Nos: 1C, 2, 2C, 2G 2V, 2Z, 8A, 8C, 8M, 8R, 8U, 9, 9D, 9F, 9K, 9L, 9M, 9N, 9Q, 9R, 9X, 9Y/F, 41M, 57S, 65M and 65S',toStay:'Seven Hill resort,Excellent resort for family and couple at cost starting from 2500/-,Yangsum Heritage form,Excellent form for family and couple at cost starting from 2500/-',toEat:'Thukpa Is a is a typical Tibetan styles noodles in soup,Kinema is a traditional fermented soybean food ',about:'67 kilometres from Gangtok, this small town is the district headquarters of the spectacular North district. It is an attractive place with good views and is a transit point to other destinations of the region.'},
  {DistName:'North Sikkim',name:'CHUNTHANG',discription:"Tourist places, Sightseeing Attractions and also to visit so many hills with full of ice",distance:"63 km",imgPath:'chunthang.jpg',shopping:'Souvenirs from Sikkim,Carpets,Thankas, Choktses,Jewellery, Large Cardamom or Bari Elaichi',nearBy:'Aritar Lake,Baba Harbhajan Singh Memorial Temple,Bakthang Waterfalls,Ban Jhakri Falls ',toGo:'Bus Nos: 1C, 2, 2C, 2G 2V, 2Z, 8A, 8C, 8M, 8R, 8U, 9, 9D, 9F, 9K, 9L, 9M, 9N, 9Q, 9R, 9X, 9Y/F, 41M, 57S, 65M and 65S',toStay:'Seven Hill resort,Excellent resort for family and couple at cost starting from 2500/-,Yangsum Heritage form,Excellent form for family and couple at cost starting from 2500/-',toEat:'Thukpa Is a is a typical Tibetan styles noodles in soup,Kinema is a traditional fermented soybean food ',about:'A small town on way to Yumthang, it stands at the confluence of the rivers Lachen chu and Lachung chu. The North Sikkim highway bifurcates from here with one road leading to Lachen and the other to Lachung. Chungthang valley is considered to be a holy place which has been blessed by Guru Padmasambhava, the patron saint of Sikkim. There is a rock here which to this day bears the hand and footprints of Padmasambhava. From a small opening in the rock there is continuous flow of mineral water. There is a small patch of land here from which grows paddy every year. The nature defying miracle is believed to be the blessing of Guru Padmasambhava who sprinkled a handful of grain on the spot which has sprouted paddy ever since.'},
  {DistName:'North Sikkim',name:'DZONGU',discription:"Tourist places, Sightseeing Attractions and also to visit so many hills with full of ice",distance:"63 km",imgPath:'dzongu.jpg',shopping:'Souvenirs from Sikkim,Carpets,Thankas, Choktses,Jewellery, Large Cardamom or Bari Elaichi',nearBy:'Aritar Lake,Baba Harbhajan Singh Memorial Temple,Bakthang Waterfalls,Ban Jhakri Falls ',toGo:'Bus Nos: 1C, 2, 2C, 2G 2V, 2Z, 8A, 8C, 8M, 8R, 8U, 9, 9D, 9F, 9K, 9L, 9M, 9N, 9Q, 9R, 9X, 9Y/F, 41M, 57S, 65M and 65S',toStay:'Seven Hill resort,Excellent resort for family and couple at cost starting from 2500/-,Yangsum Heritage form,Excellent form for family and couple at cost starting from 2500/-',toEat:'Thukpa Is a is a typical Tibetan styles noodles in soup,Kinema is a traditional fermented soybean food ',about:'70 kms away from Gangtok in North Sikkim is Dzongu, an area reserved for the Lepchas, the original inhabitants of Sikkim. Bordering the Kanchendzonga Biosphere Reserve and at an elevation ranging between 3000ft and 20,000ft above sea level, Dzongu still retains an air of exclusivity. The Lepcha Communities in Dzongu live in relative isolation from the outside world with their own traditional practice and believe.'},
  {DistName:'North Sikkim',name:'LACHUNG',discription:"Tourist places, Sightseeing Attractions and also to visit so many hills with full of ice",distance:"63 km",imgPath:'lachung.jpg',shopping:'Souvenirs from Sikkim,Carpets,Thankas, Choktses,Jewellery, Large Cardamom or Bari Elaichi',nearBy:'Aritar Lake,Baba Harbhajan Singh Memorial Temple,Bakthang Waterfalls,Ban Jhakri Falls ',toGo:'Bus Nos: 1C, 2, 2C, 2G 2V, 2Z, 8A, 8C, 8M, 8R, 8U, 9, 9D, 9F, 9K, 9L, 9M, 9N, 9Q, 9R, 9X, 9Y/F, 41M, 57S, 65M and 65S',toStay:'Seven Hill resort,Excellent resort for family and couple at cost starting from 2500/-,Yangsum Heritage form,Excellent form for family and couple at cost starting from 2500/-',toEat:'Thukpa Is a is a typical Tibetan styles noodles in soup,Kinema is a traditional fermented soybean food ',about:'The picturesque mountain village of Lachung, at a height of 8610 ft, embraced by snow capped mountain peaks, breathtaking waterfalls, sparkling streams and apple orchards is the perfect holiday destination.'},
  {DistName:'North Sikkim',name:'SINGHIK',discription:"Tourist places, Sightseeing Attractions and also to visit so many hills with full of ice",distance:"63 km",imgPath:'singhik.jpg',shopping:'Souvenirs from Sikkim,Carpets,Thankas, Choktses,Jewellery, Large Cardamom or Bari Elaichi',nearBy:'Aritar Lake,Baba Harbhajan Singh Memorial Temple,Bakthang Waterfalls,Ban Jhakri Falls ',toGo:'Bus Nos: 1C, 2, 2C, 2G 2V, 2Z, 8A, 8C, 8M, 8R, 8U, 9, 9D, 9F, 9K, 9L, 9M, 9N, 9Q, 9R, 9X, 9Y/F, 41M, 57S, 65M and 65S',toStay:'Seven Hill resort,Excellent resort for family and couple at cost starting from 2500/-,Yangsum Heritage form,Excellent form for family and couple at cost starting from 2500/-',toEat:'Thukpa Is a is a typical Tibetan styles noodles in soup,Kinema is a traditional fermented soybean food ',about:'A small and picturesque hamlet, Singhik is located around four kms away from Mangan. The popular Singhik View Point offers the most magnificent view of Mt. Khangchendzonga and Mt. Siniolchu . '},
  {DistName:'North Sikkim',name:'KABI',discription:"Tourist places, Sightseeing Attractions and also to visit so many hills with full of ice",distance:"63 km",imgPath:'kabi.jpg',shopping:'Souvenirs from Sikkim,Carpets,Thankas, Choktses,Jewellery, Large Cardamom or Bari Elaichi',nearBy:'Aritar Lake,Baba Harbhajan Singh Memorial Temple,Bakthang Waterfalls,Ban Jhakri Falls ',toGo:'Bus Nos: 1C, 2, 2C, 2G 2V, 2Z, 8A, 8C, 8M, 8R, 8U, 9, 9D, 9F, 9K, 9L, 9M, 9N, 9Q, 9R, 9X, 9Y/F, 41M, 57S, 65M and 65S',toStay:'Seven Hill resort,Excellent resort for family and couple at cost starting from 2500/-,Yangsum Heritage form,Excellent form for family and couple at cost starting from 2500/-',toEat:'Thukpa Is a is a typical Tibetan styles noodles in soup,Kinema is a traditional fermented soybean food ',about:'20 kms from Gangtok, on way to North Sikkim is the sacred spot of Kabi where the pact of blood brotherhood was sworn between the Lepchas and the Bhutias in the 15th century. Nine stones were erected facing Mount Khangchendzonga to witness the treaty of brotherhood between the Lepchas and the Bhutias. To this day the stones stand as testimony to the treaty.'},
  {DistName:'North Sikkim',name:'PHODONG',discription:"Tourist places, Sightseeing Attractions and also to visit so many hills with full of ice",distance:"63 km",imgPath:'phodong.jpg',shopping:'Souvenirs from Sikkim,Carpets,Thankas, Choktses,Jewellery, Large Cardamom or Bari Elaichi',nearBy:'Aritar Lake,Baba Harbhajan Singh Memorial Temple,Bakthang Waterfalls,Ban Jhakri Falls ',toGo:'Bus Nos: 1C, 2, 2C, 2G 2V, 2Z, 8A, 8C, 8M, 8R, 8U, 9, 9D, 9F, 9K, 9L, 9M, 9N, 9Q, 9R, 9X, 9Y/F, 41M, 57S, 65M and 65S',toStay:'Seven Hill resort,Excellent resort for family and couple at cost starting from 2500/-,Yangsum Heritage form,Excellent form for family and couple at cost starting from 2500/-',toEat:'Thukpa Is a is a typical Tibetan styles noodles in soup,Kinema is a traditional fermented soybean food ',about:'Phodang Monastery was built in the 18th century by Chogyal Gyurmed Namgyal. It belongs to the Kargyupa sect. The original monastery has been rebuilt although the old mural paintings and frescoes were preserved. It celebrates its annual \u2018chaam\u2019 on the 28th and 29th day of the tenth month of the Tibetan calendar.'},
  {DistName:'North Sikkim',name:'GURUDONGMAR',discription:"Tourist places, Sightseeing Attractions and also to visit so many hills with full of ice",distance:"63 km",imgPath:'gurudongmar.jpg',shopping:'Souvenirs from Sikkim,Carpets,Thankas, Choktses,Jewellery, Large Cardamom or Bari Elaichi',nearBy:'Aritar Lake,Baba Harbhajan Singh Memorial Temple,Bakthang Waterfalls,Ban Jhakri Falls ',toGo:'Bus Nos: 1C, 2, 2C, 2G 2V, 2Z, 8A, 8C, 8M, 8R, 8U, 9, 9D, 9F, 9K, 9L, 9M, 9N, 9Q, 9R, 9X, 9Y/F, 41M, 57S, 65M and 65S',toStay:'Seven Hill resort,Excellent resort for family and couple at cost starting from 2500/-,Yangsum Heritage form,Excellent form for family and couple at cost starting from 2500/-',toEat:'Thukpa Is a is a typical Tibetan styles noodles in soup,Kinema is a traditional fermented soybean food ',about:'Situated at a height of 17,800 feet, it is considered one the most sacred lakes by the Buddhists and Hindus alike. The beautiful and awe inspiring lake (190 kms from Gangtok) remains milky in colour throughout the year.'},
  {DistName:'North Sikkim',name:'LACHEN',discription:"Tourist places, Sightseeing Attractions and also to visit so many hills with full of ice",distance:"63 km",imgPath:'lachen.jpg',shopping:'Souvenirs from Sikkim,Carpets,Thankas, Choktses,Jewellery, Large Cardamom or Bari Elaichi',nearBy:'Aritar Lake,Baba Harbhajan Singh Memorial Temple,Bakthang Waterfalls,Ban Jhakri Falls ',toGo:'Bus Nos: 1C, 2, 2C, 2G 2V, 2Z, 8A, 8C, 8M, 8R, 8U, 9, 9D, 9F, 9K, 9L, 9M, 9N, 9Q, 9R, 9X, 9Y/F, 41M, 57S, 65M and 65S',toStay:'Seven Hill resort,Excellent resort for family and couple at cost starting from 2500/-,Yangsum Heritage form,Excellent form for family and couple at cost starting from 2500/-',toEat:'Thukpa Is a is a typical Tibetan styles noodles in soup,Kinema is a traditional fermented soybean food ',about:'At an altitude of 8500 ft Lachen is alluring in its simplicity. Not yet as big a tourist destination as Lachung, it retains a freshness which is very appealing. '},
  {DistName:'North Sikkim',name:'YUMTHANG',discription:"Tourist places, Sightseeing Attractions and also to visit so many hills with full of ice",distance:"63 km",imgPath:'yumthang.jpg',shopping:'Souvenirs from Sikkim,Carpets,Thankas, Choktses,Jewellery, Large Cardamom or Bari Elaichi',nearBy:'Aritar Lake,Baba Harbhajan Singh Memorial Temple,Bakthang Waterfalls,Ban Jhakri Falls ',toGo:'Bus Nos: 1C, 2, 2C, 2G 2V, 2Z, 8A, 8C, 8M, 8R, 8U, 9, 9D, 9F, 9K, 9L, 9M, 9N, 9Q, 9R, 9X, 9Y/F, 41M, 57S, 65M and 65S',toStay:'Seven Hill resort,Excellent resort for family and couple at cost starting from 2500/-,Yangsum Heritage form,Excellent form for family and couple at cost starting from 2500/-',toEat:'Thukpa Is a is a typical Tibetan styles noodles in soup,Kinema is a traditional fermented soybean food ',about:'Yumthang, situated at a height of 11800 feet is popularly known as Valley of Flowers, Located at a distance of 148 kms from Gangtok, it is a paradise for nature lovers with a fascinating blend of flora and fauna and breathtaking scenic beauty.'},
  {DistName:'South Sikkim',name:'NAMCHI',discription:"Tourist places, Sightseeing Attractions and also to visit so many hills with full of ice",distance:"63 km",imgPath:'namchi.jpg',shopping:'Souvenirs from Sikkim,Carpets,Thankas, Choktses,Jewellery, Large Cardamom or Bari Elaichi',nearBy:'Aritar Lake,Baba Harbhajan Singh Memorial Temple,Bakthang Waterfalls,Ban Jhakri Falls ',toGo:'Bus Nos: 1C, 2, 2C, 2G 2V, 2Z, 8A, 8C, 8M, 8R, 8U, 9, 9D, 9F, 9K, 9L, 9M, 9N, 9Q, 9R, 9X, 9Y/F, 41M, 57S, 65M and 65S',toStay:'Seven Hill resort,Excellent resort for family and couple at cost starting from 2500/-,Yangsum Heritage form,Excellent form for family and couple at cost starting from 2500/-',toEat:'Thukpa Is a is a typical Tibetan styles noodles in soup,Kinema is a traditional fermented soybean food',about:'Namchi hosts the very popular Namchi Mahotsav, a Tourism, Culture and Food Festival, every year in October. A flower festival is also held annually.',toEat:''},
  {DistName:'South Sikkim',name:'RAVANGLA',discription:"Tourist places, Sightseeing Attractions and also to visit so many hills with full of ice",distance:"63 km",imgPath:'ravangla.jpg',shopping:'Souvenirs from Sikkim,Carpets,Thankas, Choktses,Jewellery, Large Cardamom or Bari Elaichi',nearBy:'Aritar Lake,Baba Harbhajan Singh Memorial Temple,Bakthang Waterfalls,Ban Jhakri Falls ',toGo:'Bus Nos: 1C, 2, 2C, 2G 2V, 2Z, 8A, 8C, 8M, 8R, 8U, 9, 9D, 9F, 9K, 9L, 9M, 9N, 9Q, 9R, 9X, 9Y/F, 41M, 57S, 65M and 65S',toStay:'Seven Hill resort,Excellent resort for family and couple at cost starting from 2500/-',toEat:'Thukpa:Is a is a typical Tibetan styles noodles in soup,Kinema:Kinema is a traditional fermented soybean food ',about:'Ravangla is one of the most popular tourist destinations in South Sikkim. At an altitude of 7000 ft, located on a ridge between Maenam and Tendong Hill, Ravangla offers unmatched views of the Greater Himalayas.'},
  {DistName:'South Sikkim',name:'JORETHANG',discription:"Tourist places, Sightseeing Attractions and also to visit so many hills with full of ice",distance:"63 km",imgPath:'jorethang.jpg',shopping:'Souvenirs from Sikkim,Carpets,Thankas, Choktses,Jewellery, Large Cardamom or Bari Elaichi',nearBy:'Aritar Lake,Baba Harbhajan Singh Memorial Temple,Bakthang Waterfalls,Ban Jhakri Falls ',toGo:'Bus Nos: 1C, 2, 2C, 2G 2V, 2Z, 8A, 8C, 8M, 8R, 8U, 9, 9D, 9F, 9K, 9L, 9M, 9N, 9Q, 9R, 9X, 9Y/F, 41M, 57S, 65M and 65S',toStay:'Seven Hill resort,Excellent resort for family and couple at cost starting from 2500/-',toEat:'Thukpa:Is a is a typical Tibetan styles noodles in soup,Kinema:Kinema is a traditional fermented soybean food ',about:'Jorethang lies on the way to Pelling and is well connected by buses and jeeps. River rafting, trekking and sightseeing trips to nearby destinations are some of the attractions available here.'},
  {DistName:'South Sikkim',name:'SAMDRUPTE',discription:"Tourist places, Sightseeing Attractions and also to visit so many hills with full of ice",distance:"63 km",imgPath:'samdrupte.jpg',shopping:'Souvenirs from Sikkim,Carpets,Thankas, Choktses,Jewellery, Large Cardamom or Bari Elaichi',nearBy:'Aritar Lake,Baba Harbhajan Singh Memorial Temple,Bakthang Waterfalls,Ban Jhakri Falls ',toGo:'Bus Nos: 1C, 2, 2C, 2G 2V, 2Z, 8A, 8C, 8M, 8R, 8U, 9, 9D, 9F, 9K, 9L, 9M, 9N, 9Q, 9R, 9X, 9Y/F, 41M, 57S, 65M and 65S',toStay:'Seven Hill resort,Excellent resort for family and couple at cost starting from 2500/-',toEat:'Thukpa:Is a is a typical Tibetan styles noodles in soup,Kinema:Kinema is a traditional fermented soybean food ',about:'Samdruptse literally means wish fulfilling hill in the Bhutia language. Situated near Namchi in South Sikkim, it is at a distance of 75 kms from Gangtok. A unique, awe inspiring and gigangtic 135 feet high statue of Guru Padamasambhava is installed atop Sampruptse.'},
  {DistName:'South Sikkim',name:'SOLOPHOK',discription:"Tourist places, Sightseeing Attractions and also to visit so many hills with full of ice",distance:"63 km",imgPath:'solophok.jpg',shopping:'Souvenirs from Sikkim,Carpets,Thankas, Choktses,Jewellery, Large Cardamom or Bari Elaichi',nearBy:'Aritar Lake,Baba Harbhajan Singh Memorial Temple,Bakthang Waterfalls,Ban Jhakri Falls ',toGo:'Bus Nos: 1C, 2, 2C, 2G 2V, 2Z, 8A, 8C, 8M, 8R, 8U, 9, 9D, 9F, 9K, 9L, 9M, 9N, 9Q, 9R, 9X, 9Y/F, 41M, 57S, 65M and 65S',toStay:'Seven Hill resort,Excellent resort for family and couple at cost starting from 2500/-',toEat:'Thukpa:Is a is a typical Tibetan styles noodles in soup,Kinema:Kinema is a traditional fermented soybean food ',about:'his unique Pilgrim Centre has a main temple of 108 feet height on which is based the 87 feet high statue of Lord Shiva on the sitting posture at the Solophok Hill.'},
  {DistName:'South Sikkim',name:'BUDDA DARK',discription:"Tourist places, Sightseeing Attractions and also to visit so many hills with full of ice",distance:"63 km",imgPath:'buddaDark.jpg',shopping:'Souvenirs from Sikkim,Carpets,Thankas, Choktses,Jewellery, Large Cardamom or Bari Elaichi',nearBy:'Aritar Lake,Baba Harbhajan Singh Memorial Temple,Bakthang Waterfalls,Ban Jhakri Falls ',toGo:'Bus Nos: 1C, 2, 2C, 2G 2V, 2Z, 8A, 8C, 8M, 8R, 8U, 9, 9D, 9F, 9K, 9L, 9M, 9N, 9Q, 9R, 9X, 9Y/F, 41M, 57S, 65M and 65S',toStay:'Seven Hill resort,Excellent resort for family and couple at cost starting from 2500/-',toEat:'Thukpa:Is a is a typical Tibetan styles noodles in soup,Kinema:Kinema is a traditional fermented soybean food ',about:'2006 marked the 2550th birth anniversary of Lord Gautama Buddha. The state government in a policy decision had decided to observe the birth anniversary throughout the year in Sikkim.'},
  {DistName:'East Sikkim',name:'GANGTOK',discription:"Tourist places, Sightseeing Attractions and also to visit so many hills with full of ice",distance:"63 km",imgPath:'gangtok.jpg',shopping:'Souvenirs from Sikkim,Carpets,Thankas, Choktses,Jewellery, Large Cardamom or Bari Elaichi',nearBy:'Aritar Lake,Baba Harbhajan Singh Memorial Temple,Bakthang Waterfalls,Ban Jhakri Falls ',toGo:'Bus Nos: 1C, 2, 2C, 2G 2V, 2Z, 8A, 8C, 8M, 8R, 8U, 9, 9D, 9F, 9K, 9L, 9M, 9N, 9Q, 9R, 9X, 9Y/F, 41M, 57S, 65M and 65S',toStay:'Seven Hill resort,Excellent resort for family and couple at cost starting from 2500/-,Yangsum Heritage form,Excellent form for family and couple at cost starting from 2500/-',toEat:'Thukpa Is a is a typical Tibetan styles noodles in soup,Kinema is a traditional fermented soybean food ',about:'Wreathed in clouds, Gangtok, the capital city of Sikkim is located on a ridge at a height of 5500 feet. With a spectacular view of the Khangchendzonga, the town provides the perfect base for travel through the state.'},
  {DistName:'East Sikkim',name:'ARITAR',discription:"Tourist places, Sightseeing Attractions and also to visit so many hills with full of ice",distance:"63 km",imgPath:'aritar.jpg',shopping:'Souvenirs from Sikkim,Carpets,Thankas, Choktses,Jewellery, Large Cardamom or Bari Elaichi',nearBy:'Aritar Lake,Baba Harbhajan Singh Memorial Temple,Bakthang Waterfalls,Ban Jhakri Falls ',toGo:'Bus Nos: 1C, 2, 2C, 2G 2V, 2Z, 8A, 8C, 8M, 8R, 8U, 9, 9D, 9F, 9K, 9L, 9M, 9N, 9Q, 9R, 9X, 9Y/F, 41M, 57S, 65M and 65S',toStay:'Seven Hill resort,Excellent resort for family and couple at cost starting from 2500/-,Yangsum Heritage form,Excellent form for family and couple at cost starting from 2500/-',toEat:'Thukpa Is a is a typical Tibetan styles noodles in soup,Kinema is a traditional fermented soybean food ',about:'Located in east Sikkim, Aritar is steeped in history and natural beauty. A breathtaking view of Khangchendzonga only adds to the many natural riches that Aritar is blessed with. Lush green forests, sweeping hills of paddy fields and placid lakes hidden inside deep forests makes it a perfect destination for those in search of nature trails and a serene holiday.'},
  {DistName:'East Sikkim',name:'RUMTEK',discription:"Tourist places, Sightseeing Attractions and also to visit so many hills with full of ice",distance:"63 km",imgPath:'rumtek.jpg',shopping:'Souvenirs from Sikkim,Carpets,Thankas, Choktses,Jewellery, Large Cardamom or Bari Elaichi',nearBy:'Aritar Lake,Baba Harbhajan Singh Memorial Temple,Bakthang Waterfalls,Ban Jhakri Falls ',toGo:'Bus Nos: 1C, 2, 2C, 2G 2V, 2Z, 8A, 8C, 8M, 8R, 8U, 9, 9D, 9F, 9K, 9L, 9M, 9N, 9Q, 9R, 9X, 9Y/F, 41M, 57S, 65M and 65S',toStay:'Seven Hill resort,Excellent resort for family and couple at cost starting from 2500/-,Yangsum Heritage form,Excellent form for family and couple at cost starting from 2500/-',toEat:'Thukpa Is a is a typical Tibetan styles noodles in soup,Kinema is a traditional fermented soybean food ',about:'Situated around 23 kms from Gangtok, in the hill facing Gangtok is Rumtek, a quiet getaway and home to the Rumtek Monastery, seat of His Holiness, The Gyalwa Karmapa of the Kargyu sect of Tibetan Buddhism.'},
  {DistName:'East Sikkim',name:'CHANGU LAKE',discription:"Tourist places, Sightseeing Attractions and also to visit so many hills with full of ice",distance:"63 km",imgPath:'changu.jpg',shopping:'Souvenirs from Sikkim,Carpets,Thankas, Choktses,Jewellery, Large Cardamom or Bari Elaichi',nearBy:'Aritar Lake,Baba Harbhajan Singh Memorial Temple,Bakthang Waterfalls,Ban Jhakri Falls ',toGo:'Bus Nos: 1C, 2, 2C, 2G 2V, 2Z, 8A, 8C, 8M, 8R, 8U, 9, 9D, 9F, 9K, 9L, 9M, 9N, 9Q, 9R, 9X, 9Y/F, 41M, 57S, 65M and 65S',toStay:'Seven Hill resort,Excellent resort for family and couple at cost starting from 2500/-,Yangsum Heritage form,Excellent form for family and couple at cost starting from 2500/-',toEat:'Thukpa Is a is a typical Tibetan styles noodles in soup,Kinema is a traditional fermented soybean food ',about:'38 km from Gangtok and at an altitude of 12,400 ft, the ethereally beautiful Tsomgo lake is a must on every visitors itinerary. A winding road through rugged mountain terrain and sharp cliffs takes you to Tsomgo, which means source of the water in Bhutia language. '},
  {DistName:'East Sikkim',name:'NATHULA',discription:"Tourist places, Sightseeing Attractions and also to visit so many hills with full of ice",distance:"63 km",imgPath:'nathula.jpg',shopping:'Souvenirs from Sikkim,Carpets,Thankas, Choktses,Jewellery, Large Cardamom or Bari Elaichi',nearBy:'Aritar Lake,Baba Harbhajan Singh Memorial Temple,Bakthang Waterfalls,Ban Jhakri Falls ',toGo:'Bus Nos: 1C, 2, 2C, 2G 2V, 2Z, 8A, 8C, 8M, 8R, 8U, 9, 9D, 9F, 9K, 9L, 9M, 9N, 9Q, 9R, 9X, 9Y/F, 41M, 57S, 65M and 65S',toStay:'Seven Hill resort,Excellent resort for family and couple at cost starting from 2500/-,Yangsum Heritage form,Excellent form for family and couple at cost starting from 2500/-',toEat:'Thukpa Is a is a typical Tibetan styles noodles in soup,Kinema is a traditional fermented soybean food ',about:'Nathula Pass was a major corridor of passage between India and Tibet before it was closed in 1962. Located around 56 kms from Gangtok at an altitude of 14450 ft, the road to Nathula passes through the Tsomgo lake. '},
  {DistName:'East Sikkim',name:'KHANCHAEDZONGA',discription:"Tourist places, Sightseeing Attractions and also to visit so many hills with full of ice",distance:"63 km",imgPath:'khachanedzonga.jpg',shopping:'Souvenirs from Sikkim,Carpets,Thankas, Choktses,Jewellery, Large Cardamom or Bari Elaichi',nearBy:'Aritar Lake,Baba Harbhajan Singh Memorial Temple,Bakthang Waterfalls,Ban Jhakri Falls ',toGo:'Bus Nos: 1C, 2, 2C, 2G 2V, 2Z, 8A, 8C, 8M, 8R, 8U, 9, 9D, 9F, 9K, 9L, 9M, 9N, 9Q, 9R, 9X, 9Y/F, 41M, 57S, 65M and 65S',toStay:'Seven Hill resort,Excellent resort for family and couple at cost starting from 2500/-,Yangsum Heritage form,Excellent form for family and couple at cost starting from 2500/-',toEat:'Thukpa Is a is a typical Tibetan styles noodles in soup,Kinema is a traditional fermented soybean food ',about:'Khachanedzonga between India and Tibet before it was closed in 1962. Located around 56 kms from Gangtok at an altitude of 14450 ft, the road to Nathula passes through the Tsomgo lake.'},
  {DistName:'East Sikkim',name:'JURASSIC PARK',discription:"Tourist places, Sightseeing Attractions and also to visit so many hills with full of ice",distance:"63 km",imgPath:'jurassic.jpg',shopping:'Souvenirs from Sikkim,Carpets,Thankas, Choktses,Jewellery, Large Cardamom or Bari Elaichi',nearBy:'Aritar Lake,Baba Harbhajan Singh Memorial Temple,Bakthang Waterfalls,Ban Jhakri Falls ',toGo:'Bus Nos: 1C, 2, 2C, 2G 2V, 2Z, 8A, 8C, 8M, 8R, 8U, 9, 9D, 9F, 9K, 9L, 9M, 9N, 9Q, 9R, 9X, 9Y/F, 41M, 57S, 65M and 65S',toStay:'Seven Hill resort,Excellent resort for family and couple at cost starting from 2500/-,Yangsum Heritage form,Excellent form for family and couple at cost starting from 2500/-',toEat:'Thukpa Is a is a typical Tibetan styles noodles in soup,Kinema is a traditional fermented soybean food ',about:'Jurassic Park between India and Tibet before it was closed in 1962. Located around 56 kms from Gangtok at an altitude of 14450 ft, the road to Nathula passes through the Tsomgo lake.'},
  {DistName:'East Sikkim',name:'KHEDI TRECK ROUTE',discription:"Tourist places, Sightseeing Attractions and also to visit so many hills with full of ice",distance:"63 km",imgPath:'khediTrekRoute.jpg',shopping:'Souvenirs from Sikkim,Carpets,Thankas, Choktses,Jewellery, Large Cardamom or Bari Elaichi',nearBy:'Aritar Lake,Baba Harbhajan Singh Memorial Temple,Bakthang Waterfalls,Ban Jhakri Falls ',toGo:'Bus Nos: 1C, 2, 2C, 2G 2V, 2Z, 8A, 8C, 8M, 8R, 8U, 9, 9D, 9F, 9K, 9L, 9M, 9N, 9Q, 9R, 9X, 9Y/F, 41M, 57S, 65M and 65S',toStay:'Seven Hill resort,Excellent resort for family and couple at cost starting from 2500/-,Yangsum Heritage form,Excellent form for family and couple at cost starting from 2500/-',toEat:'Thukpa Is a is a typical Tibetan styles noodles in soup,Kinema is a traditional fermented soybean food ',about:'KhediTrekRoute between India and Tibet before it was closed in 1962. Located around 56 kms from Gangtok at an altitude of 14450 ft, the road to Nathula passes through the Tsomgo lake.'},
  {DistName:'East Sikkim',name:'VILLAGE TOURISM',discription:"Tourist places, Sightseeing Attractions and also to visit so many hills with full of ice",distance:"63 km",imgPath:'villageTourism.jpg',shopping:'Souvenirs from Sikkim,Carpets,Thankas, Choktses,Jewellery, Large Cardamom or Bari Elaichi',nearBy:'Aritar Lake,Baba Harbhajan Singh Memorial Temple,Bakthang Waterfalls,Ban Jhakri Falls ',toGo:'Bus Nos: 1C, 2, 2C, 2G 2V, 2Z, 8A, 8C, 8M, 8R, 8U, 9, 9D, 9F, 9K, 9L, 9M, 9N, 9Q, 9R, 9X, 9Y/F, 41M, 57S, 65M and 65S',toStay:'Seven Hill resort,Excellent resort for family and couple at cost starting from 2500/-,Yangsum Heritage form,Excellent form for family and couple at cost starting from 2500/-',toEat:'Thukpa Is a is a typical Tibetan styles noodles in soup,Kinema is a traditional fermented soybean food ',about:'VillageTourism between India and Tibet before it was closed in 1962. Located around 56 kms from Gangtok at an altitude of 14450 ft, the road to Nathula passes through the Tsomgo lake.'},
  {DistName:'East Sikkim',name:'BANJAKRI FALLS',discription:"Tourist places, Sightseeing Attractions and also to visit so many hills with full of ice",distance:"63 km",imgPath:'banjakriFalls.jpg',shopping:'Souvenirs from Sikkim,Carpets,Thankas, Choktses,Jewellery, Large Cardamom or Bari Elaichi',nearBy:'Aritar Lake,Baba Harbhajan Singh Memorial Temple,Bakthang Waterfalls,Ban Jhakri Falls ',toGo:'Bus Nos: 1C, 2, 2C, 2G 2V, 2Z, 8A, 8C, 8M, 8R, 8U, 9, 9D, 9F, 9K, 9L, 9M, 9N, 9Q, 9R, 9X, 9Y/F, 41M, 57S, 65M and 65S',toStay:'Seven Hill resort,Excellent resort for family and couple at cost starting from 2500/-,Yangsum Heritage form,Excellent form for family and couple at cost starting from 2500/-',toEat:'Thukpa Is a is a typical Tibetan styles noodles in soup,Kinema is a traditional fermented soybean food ',about:'BanjakriFalls between India and Tibet before it was closed in 1962. Located around 56 kms from Gangtok at an altitude of 14450 ft, the road to Nathula passes through the Tsomgo lake.'},
  {DistName:'East Sikkim',name:'KHANCHAEDZONGA TOURIST VILLA',discription:"Tourist places, Sightseeing Attractions and also to visit so many hills with full of ice",distance:"63 km",imgPath:'khachanedzongaToristVilla.jpg',shopping:'Souvenirs from Sikkim,Carpets,Thankas, Choktses,Jewellery, Large Cardamom or Bari Elaichi',nearBy:'Aritar Lake,Baba Harbhajan Singh Memorial Temple,Bakthang Waterfalls,Ban Jhakri Falls ',toGo:'Bus Nos: 1C, 2, 2C, 2G 2V, 2Z, 8A, 8C, 8M, 8R, 8U, 9, 9D, 9F, 9K, 9L, 9M, 9N, 9Q, 9R, 9X, 9Y/F, 41M, 57S, 65M and 65S',toStay:'Seven Hill resort,Excellent resort for family and couple at cost starting from 2500/-,Yangsum Heritage form,Excellent form for family and couple at cost starting from 2500/-',toEat:'Thukpa Is a is a typical Tibetan styles noodles in soup,Kinema is a traditional fermented soybean food ',about:'KhachanedzongaToristVilla between India and Tibet before it was closed in 1962. Located around 56 kms from Gangtok at an altitude of 14450 ft, the road to Nathula passes through the Tsomgo lake.' },
  {DistName:'West Sikkim',name:'SORENG',discription:"Tourist places, Sightseeing Attractions and also to visit so many hills with full of ice",distance:"63 km",imgPath:'soreng.jpg',shopping:'Souvenirs from Sikkim,Carpets,Thankas, Choktses,Jewellery, Large Cardamom or Bari Elaichi',nearBy:'Aritar Lake,Baba Harbhajan Singh Memorial Temple,Bakthang Waterfalls,Ban Jhakri Falls ',toGo:'Bus Nos: 1C, 2, 2C, 2G 2V, 2Z, 8A, 8C, 8M, 8R, 8U, 9, 9D, 9F, 9K, 9L, 9M, 9N, 9Q, 9R, 9X, 9Y/F, 41M, 57S, 65M and 65S',toStay:'Seven Hill resort,Excellent resort for family and couple at cost starting from 2500/-,Yangsum Heritage form,Excellent form for family and couple at cost starting from 2500/-',toEat:'Thukpa Is a is a typical Tibetan styles noodles in soup,Kinema is a traditional fermented soybean food ',about:'A four hour drive from Pelling in west Sikkim takes you to the picturesque village of Soreng. Surrounded by lush green hills, Soreng is located amidst scenic splendour. The area is famous for the wide variety of flowers and birds available here. A trip to Jhandi Danra is highly recommended for nature lovers.'},
  {DistName:'West Sikkim',name:'VARSEY',discription:"Tourist places, Sightseeing Attractions and also to visit so many hills with full of ice",distance:"63 km",imgPath:'varsey.jpg',shopping:'Souvenirs from Sikkim,Carpets,Thankas, Choktses,Jewellery, Large Cardamom or Bari Elaichi',nearBy:'Aritar Lake,Baba Harbhajan Singh Memorial Temple,Bakthang Waterfalls,Ban Jhakri Falls ',toGo:'Bus Nos: 1C, 2, 2C, 2G 2V, 2Z, 8A, 8C, 8M, 8R, 8U, 9, 9D, 9F, 9K, 9L, 9M, 9N, 9Q, 9R, 9X, 9Y/F, 41M, 57S, 65M and 65S',toStay:'Seven Hill resort,Excellent resort for family and couple at cost starting from 2500/-,Yangsum Heritage form,Excellent form for family and couple at cost starting from 2500/-',toEat:'Thukpa Is a is a typical Tibetan styles noodles in soup,Kinema is a traditional fermented soybean food ',about:'Near Hilley, in West Sikkim is the Varsey Rhododendron Sanctuary. Sandwiched between the Singalila National Park in the south and Khangchendzonga Biosphere Reserve in the north, this small 104-sq-km sanctuary is at an altitude of 10,000 ft and supports a wide variety of bio-diversity.'},
  {DistName:'West Sikkim',name:'DENTAM',discription:"Tourist places, Sightseeing Attractions and also to visit so many hills with full of ice",distance:"63 km",imgPath:'dentam.jpg',shopping:'Souvenirs from Sikkim,Carpets,Thankas, Choktses,Jewellery, Large Cardamom or Bari Elaichi',nearBy:'Aritar Lake,Baba Harbhajan Singh Memorial Temple,Bakthang Waterfalls,Ban Jhakri Falls ',toGo:'Bus Nos: 1C, 2, 2C, 2G 2V, 2Z, 8A, 8C, 8M, 8R, 8U, 9, 9D, 9F, 9K, 9L, 9M, 9N, 9Q, 9R, 9X, 9Y/F, 41M, 57S, 65M and 65S',toStay:'Seven Hill resort,Excellent resort for family and couple at cost starting from 2500/-,Yangsum Heritage form,Excellent form for family and couple at cost starting from 2500/-',toEat:'Thukpa Is a is a typical Tibetan styles noodles in soup,Kinema is a traditional fermented soybean food ',about:'Dentam is a scenic village located 10 km from Varsey in West Sikkim District. It lies at an elevation of around 1,500 m. Dentam commands a constant view of the Kanchenjunga. The entire area is surrounded by forest of rhododendrons. Pemayangtse Monastery (10 km), Ravangla (69 km) and Hilley are nearby interesting destinations to visit. '},
  {DistName:'West Sikkim',name:'SOMBARIA',discription:"Tourist places, Sightseeing Attractions and also to visit so many hills with full of ice",distance:"63 km",imgPath:'sombaria.jpg',shopping:'Souvenirs from Sikkim,Carpets,Thankas, Choktses,Jewellery, Large Cardamom or Bari Elaichi',nearBy:'Aritar Lake,Baba Harbhajan Singh Memorial Temple,Bakthang Waterfalls,Ban Jhakri Falls ',toGo:'Bus Nos: 1C, 2, 2C, 2G 2V, 2Z, 8A, 8C, 8M, 8R, 8U, 9, 9D, 9F, 9K, 9L, 9M, 9N, 9Q, 9R, 9X, 9Y/F, 41M, 57S, 65M and 65S',toStay:'Seven Hill resort,Excellent resort for family and couple at cost starting from 2500/-,Yangsum Heritage form,Excellent form for family and couple at cost starting from 2500/-',toEat:'Thukpa Is a is a typical Tibetan styles noodles in soup,Kinema is a traditional fermented soybean food ',about:'Situated at an altitude of 3,700 feet, Sombaria, a small village is full of vegetation of temperate type and is located remotely in the extreme Western Sikkim. Sombaria is close to the Indo-Nepal border and border region of Darjeeling Hills. At a distance of 115 km away from Siliguri and 112 km from the capital city of Sikkim, Gangtok, it is an ideal place for Bird Watching.'},
  {DistName:'West Sikkim',name:'GYALSHING',discription:"Tourist places, Sightseeing Attractions and also to visit so many hills with full of ice",distance:"63 km",imgPath:'gyalshing.jpg',shopping:'Souvenirs from Sikkim,Carpets,Thankas, Choktses,Jewellery, Large Cardamom or Bari Elaichi',nearBy:'Aritar Lake,Baba Harbhajan Singh Memorial Temple,Bakthang Waterfalls,Ban Jhakri Falls ',toGo:'Bus Nos: 1C, 2, 2C, 2G 2V, 2Z, 8A, 8C, 8M, 8R, 8U, 9, 9D, 9F, 9K, 9L, 9M, 9N, 9Q, 9R, 9X, 9Y/F, 41M, 57S, 65M and 65S',toStay:'Seven Hill resort,Excellent resort for family and couple at cost starting from 2500/-,Yangsum Heritage form,Excellent form for family and couple at cost starting from 2500/-',toEat:'Thukpa Is a is a typical Tibetan styles noodles in soup,Kinema is a traditional fermented soybean food ',about:'The headquarters of the West district, Gyalshing, which means the King\u2019s Garden, is believed to have once been the royal gardens attached to the Palace at Rabdentse, Sikkim\u2019s capital till the late 18th century. Today it is a bustling town and the main transit point to various tourist destinations of the region.'},
  {DistName:'West Sikkim',name:'LEGSHIP',discription:"Tourist places, Sightseeing Attractions and also to visit so many hills with full of ice",distance:"63 km",imgPath:'legship.jpg',shopping:'Souvenirs from Sikkim,Carpets,Thankas, Choktses,Jewellery, Large Cardamom or Bari Elaichi',nearBy:'Aritar Lake,Baba Harbhajan Singh Memorial Temple,Bakthang Waterfalls,Ban Jhakri Falls ',toGo:'Bus Nos: 1C, 2, 2C, 2G 2V, 2Z, 8A, 8C, 8M, 8R, 8U, 9, 9D, 9F, 9K, 9L, 9M, 9N, 9Q, 9R, 9X, 9Y/F, 41M, 57S, 65M and 65S',toStay:'Seven Hill resort,Excellent resort for family and couple at cost starting from 2500/-,Yangsum Heritage form,Excellent form for family and couple at cost starting from 2500/-',toEat:'Thukpa Is a is a typical Tibetan styles noodles in soup,Kinema is a traditional fermented soybean food ',about:'Often called the Gateway to West Sikkim, Legship is slowly gaining in popularity. On the left banks of the river Rangit is a Shiva temple known as the Kirateshwar Mahadev Mandir, which has many mythological episodes of the Mahabharata attached to it. '},
  {DistName:'West Sikkim',name:'TASHIDING',discription:"Tourist places, Sightseeing Attractions and also to visit so many hills with full of ice",distance:"63 km",imgPath:'tashiding.jpg',shopping:'Souvenirs from Sikkim,Carpets,Thankas, Choktses,Jewellery, Large Cardamom or Bari Elaichi',nearBy:'Aritar Lake,Baba Harbhajan Singh Memorial Temple,Bakthang Waterfalls,Ban Jhakri Falls ',toGo:'Bus Nos: 1C, 2, 2C, 2G 2V, 2Z, 8A, 8C, 8M, 8R, 8U, 9, 9D, 9F, 9K, 9L, 9M, 9N, 9Q, 9R, 9X, 9Y/F, 41M, 57S, 65M and 65S',toStay:'Seven Hill resort,Excellent resort for family and couple at cost starting from 2500/-,Yangsum Heritage form,Excellent form for family and couple at cost starting from 2500/-',toEat:'Thukpa Is a is a typical Tibetan styles noodles in soup,Kinema is a traditional fermented soybean food ',about:'Tashiding is a small village on a hilltop near Pelling. The Tashiding monastery belongs to the Nyingmapa order and is highly revered among the people of Sikkim. Build on the top of the hill and looming over the Rathong and Rangit river, the monastery can be seen from far and wide.'},
  {DistName:'West Sikkim',name:'UTTAREY',discription:"Tourist places, Sightseeing Attractions and also to visit so many hills with full of ice",distance:"63 km",imgPath:'uttarey.jpg',shopping:'Souvenirs from Sikkim,Carpets,Thankas, Choktses,Jewellery, Large Cardamom or Bari Elaichi',nearBy:'Aritar Lake,Baba Harbhajan Singh Memorial Temple,Bakthang Waterfalls,Ban Jhakri Falls ',toGo:'Bus Nos: 1C, 2, 2C, 2G 2V, 2Z, 8A, 8C, 8M, 8R, 8U, 9, 9D, 9F, 9K, 9L, 9M, 9N, 9Q, 9R, 9X, 9Y/F, 41M, 57S, 65M and 65S',toStay:'Seven Hill resort,Excellent resort for family and couple at cost starting from 2500/-,Yangsum Heritage form,Excellent form for family and couple at cost starting from 2500/-',toEat:'Thukpa Is a is a typical Tibetan styles noodles in soup,Kinema is a traditional fermented soybean food ',about:'Situated in the west district of Sikkim, you can reach Uttarey from Pelling, Gezing or Dentum. On your way you will pass Singsor bridge, said to be the second highest bridge in Asia. The height of Uttarey is about 6600ft.'},
  {DistName:'West Sikkim',name:'RICHENPONG',discription:"Tourist places, Sightseeing Attractions and also to visit so many hills with full of ice",distance:"63 km",imgPath:'richenpong.jpg',shopping:'Souvenirs from Sikkim,Carpets,Thankas, Choktses,Jewellery, Large Cardamom or Bari Elaichi',nearBy:'Aritar Lake,Baba Harbhajan Singh Memorial Temple,Bakthang Waterfalls,Ban Jhakri Falls ',toGo:'Bus Nos: 1C, 2, 2C, 2G 2V, 2Z, 8A, 8C, 8M, 8R, 8U, 9, 9D, 9F, 9K, 9L, 9M, 9N, 9Q, 9R, 9X, 9Y/F, 41M, 57S, 65M and 65S',toStay:'Seven Hill resort,Excellent resort for family and couple at cost starting from 2500/-,Yangsum Heritage form,Excellent form for family and couple at cost starting from 2500/-',toEat:'Thukpa Is a is a typical Tibetan styles noodles in soup,Kinema is a traditional fermented soybean food ',about:'The upcoming tourist spot in the western part of Sikkim, has a magnificent command over the mountain views, sunrise and sunset, flora and fauna, village tourism ,historical sites and heritage of Resum Monastery, rich forests and ample area for short treks.'},
  {DistName:'West Sikkim',name:'YUKSAM',discription:"Tourist places, Sightseeing Attractions and also to visit so many hills with full of ice",distance:"63 km",imgPath:'yuksam.jpg',shopping:'Souvenirs from Sikkim,Carpets,Thankas, Choktses,Jewellery, Large Cardamom or Bari Elaichi',nearBy:'Aritar Lake,Baba Harbhajan Singh Memorial Temple,Bakthang Waterfalls,Ban Jhakri Falls ',toGo:'Bus Nos: 1C, 2, 2C, 2G 2V, 2Z, 8A, 8C, 8M, 8R, 8U, 9, 9D, 9F, 9K, 9L, 9M, 9N, 9Q, 9R, 9X, 9Y/F, 41M, 57S, 65M and 65S',toStay:'Seven Hill resort,Excellent resort for family and couple at cost starting from 2500/-,Yangsum Heritage form,Excellent form for family and couple at cost starting from 2500/-',toEat:'Thukpa Is a is a typical Tibetan styles noodles in soup,Kinema is a traditional fermented soybean food ',about:'33 kms from Pelling, Yuksom, literally meaning the \u2018meeting place of three lamas\u2019 is of great historical importance to the Sikkimese. It was here that the first Chogyal was crowned in 1642. The throne made of stones is even today considered sacred as is the footprint of Lhatsun Chenpo, which can be seen close to the throne.'},
  {DistName:'West Sikkim',name:'PELLING',discription:"Tourist places, Sightseeing Attractions and also to visit so many hills with full of ice",distance:"63 km",imgPath:'pelling.jpg',shopping:'Souvenirs from Sikkim,Carpets,Thankas, Choktses,Jewellery, Large Cardamom or Bari Elaichi',nearBy:'Aritar Lake,Baba Harbhajan Singh Memorial Temple,Bakthang Waterfalls,Ban Jhakri Falls ',toGo:'Bus Nos: 1C, 2, 2C, 2G 2V, 2Z, 8A, 8C, 8M, 8R, 8U, 9, 9D, 9F, 9K, 9L, 9M, 9N, 9Q, 9R, 9X, 9Y/F, 41M, 57S, 65M and 65S',toStay:'Seven Hill resort,Excellent resort for family and couple at cost starting from 2500/-,Yangsum Heritage form,Excellent form for family and couple at cost starting from 2500/-',toEat:'Thukpa Is a is a typical Tibetan styles noodles in soup,Kinema is a traditional fermented soybean food ',about:'Around 10 kms from Gyalshing (District Headquarter), Pelling is today emerging as the second biggest tourist destination in the state after Gangtok. Although in itself it is little more than a strip of road lined with hotels, its main USP is the breathtaking view it offers of the Khangchendzonga and surrounding ranges, as well as the easy access it provides to tourist spots in the area.'},
  {DistName:'West Sikkim',name:'KHECHEPLORI',discription:"Tourist places, Sightseeing Attractions and also to visit so many hills with full of ice",distance:"63 km",imgPath:'khecheoplri.jpg',shopping:'Souvenirs from Sikkim,Carpets,Thankas, Choktses,Jewellery, Large Cardamom or Bari Elaichi',nearBy:'Aritar Lake,Baba Harbhajan Singh Memorial Temple,Bakthang Waterfalls,Ban Jhakri Falls ',toGo:'Bus Nos: 1C, 2, 2C, 2G 2V, 2Z, 8A, 8C, 8M, 8R, 8U, 9, 9D, 9F, 9K, 9L, 9M, 9N, 9Q, 9R, 9X, 9Y/F, 41M, 57S, 65M and 65S',toStay:'Seven Hill resort,Excellent resort for family and couple at cost starting from 2500/-,Yangsum Heritage form,Excellent form for family and couple at cost starting from 2500/-',toEat:'Thukpa Is a is a typical Tibetan styles noodles in soup,Kinema is a traditional fermented soybean food ',about:'Situated at a distance of 25 kms. from Pelling, it is considered to be one of the sacred lakes of the State both by the Buddhist and the Hindus. The Lake remains hidden under the rich forest cover. The birds do not permit even a single leaf to float on the lake surface.'},
  {DistName:'West Sikkim',name:'PEMAYENGSTE',discription:"Tourist places, Sightseeing Attractions and also to visit so many hills with full of ice",distance:"63 km",imgPath:'pemayengste.JPG',shopping:'Souvenirs from Sikkim,Carpets,Thankas, Choktses,Jewellery, Large Cardamom or Bari Elaichi',nearBy:'Aritar Lake,Baba Harbhajan Singh Memorial Temple,Bakthang Waterfalls,Ban Jhakri Falls ',toGo:'Bus Nos: 1C, 2, 2C, 2G 2V, 2Z, 8A, 8C, 8M, 8R, 8U, 9, 9D, 9F, 9K, 9L, 9M, 9N, 9Q, 9R, 9X, 9Y/F, 41M, 57S, 65M and 65S',toStay:'Seven Hill resort,Excellent resort for family and couple at cost starting from 2500/-,Yangsum Heritage form,Excellent form for family and couple at cost starting from 2500/-',toEat:'Thukpa Is a is a typical Tibetan styles noodles in soup,Kinema is a traditional fermented soybean food ',about:'It is one of the oldest monasteries of the State. It was originally established by Lhatsun Chempo, one of the revered Lamas to have performed the consecration ceremony of the first Chogyal (Monarch) of Sikkim.'},
  {DistName:'West Sikkim',name:'HEEBERMOIK',discription:"Tourist places, Sightseeing Attractions and also to visit so many hills with full of ice",distance:"63 km",imgPath:'heebermoik.jpg',shopping:'Souvenirs from Sikkim,Carpets,Thankas, Choktses,Jewellery, Large Cardamom or Bari Elaichi',nearBy:'Aritar Lake,Baba Harbhajan Singh Memorial Temple,Bakthang Waterfalls,Ban Jhakri Falls ',toGo:'Bus Nos: 1C, 2, 2C, 2G 2V, 2Z, 8A, 8C, 8M, 8R, 8U, 9, 9D, 9F, 9K, 9L, 9M, 9N, 9Q, 9R, 9X, 9Y/F, 41M, 57S, 65M and 65S',toStay:'Seven Hill resort,Excellent resort for family and couple at cost starting from 2500/-,Yangsum Heritage form,Excellent form for family and couple at cost starting from 2500/-',toEat:'Thukpa Is a is a typical Tibetan styles noodles in soup,Kinema is a traditional fermented soybean food ',about:'It is one of the oldest monasteries of the State. It was originally established by Lhatsun Chempo, one of the revered Lamas to have performed the consecration ceremony of the first Chogyal (Monarch) of Sikkim.'}
]
gallerydata = [
  {Imgpath:'aritar.jpg',PlaceName:'MANGAN'}
  {Imgpath:'Back cover.jpg',PlaceName:'MANGAN'}
  {Imgpath:'banjakriFalls.jpg',PlaceName:'MANGAN'}
  {Imgpath:'buddadark.jpg',PlaceName:'MANGAN'}
  {Imgpath:'changu.jpg',PlaceName:'MANGAN'}
  {Imgpath:'chunthang.jpg',PlaceName:'CHUNTHANG'}
  {Imgpath:'dentam.jpg',PlaceName:'CHUNTHANG'}
  {Imgpath:'dzongu.jpg',PlaceName:'CHUNTHANG'}
  {Imgpath:'gangtok.jpg',PlaceName:'DZONGU'}
  {Imgpath:'gurudongmar.jpg',PlaceName:'DZONGU'}
  {Imgpath:'gyalshing.jpg',PlaceName:'NAMCHI'}
  {Imgpath:'heebermoik.jpg',PlaceName:'NAMCHI'}
  {Imgpath:'jorethang.jpg',PlaceName:'NAMCHI'}
  {Imgpath:'gyalshing.jpg',PlaceName:'RAVANGLA'}
  {Imgpath:'jurassic.jpg',PlaceName:'RAVANGLA'}
  {Imgpath:'kabi.jpg',PlaceName:'RAVANGLA'}
  {Imgpath:'khanchaedzonga.jpg',PlaceName:'RAVANGLA'}
  {Imgpath:'khecheplori.jpg',PlaceName:'JORETHANG'}
  {Imgpath:'khediTreckRoute.jpg',PlaceName:'JORETHANG'}
  {Imgpath:'lachen.jpg',PlaceName:'JORETHANG'}
  {Imgpath:'lachung.jpg',PlaceName:'JORETHANG'}
  {Imgpath:'legship.jpg',PlaceName:'GANGTOK'}
  {Imgpath:'mangan.jpg',PlaceName:'GANGTOK'}
  {Imgpath:'namchi.jpg',PlaceName:'GANGTOK'}
  {Imgpath:'pelling.jpg',PlaceName:'GANGTOK'}
  {Imgpath:'pemayengste.jpg',PlaceName:'ARITAR'}
  {Imgpath:'phodong.jpg',PlaceName:'ARITAR'}
  {Imgpath:'promotion.jpg',PlaceName:'ARITAR'}
  {Imgpath:'ravangla.jpg',PlaceName:'ARITAR'}
  {Imgpath:'richenpong.jpg',PlaceName:'RUMTEK'}
  {Imgpath:'rumtek.jpg',PlaceName:'RUMTEK'}
  {Imgpath:'samdrupte.jpg',PlaceName:'RUMTEK'}
  {Imgpath:'share.jpg',PlaceName:'RUMTEK'}
  {Imgpath:'sikkimhill.jpg',PlaceName:'SORENG'}
  {Imgpath:'singhik.jpg',PlaceName:'SORENG'}
  {Imgpath:'solophok.jpg',PlaceName:'SORENG'}
  {Imgpath:'sombaria.jpg',PlaceName:'SORENG'}
  {Imgpath:'soreng.jpg',PlaceName:'VARSEY'}
  {Imgpath:'tashiding.jpg',PlaceName:'VARSEY'}
  {Imgpath:'uttarey.jpg',PlaceName:'VARSEY'}
  {Imgpath:'villageTourism.jpg',PlaceName:'VARSEY'}
  {Imgpath:'yumthang.jpg',PlaceName:'VARSEY'}
]
hotels = [{hotelName:"Anugraha Hotel",placeName:"MANGAN",address:"Deorali School Road",contactNo:"9475384683"},
  {hotelName:"Golden Pagoda",placeName:"MANGAN",address:"M.G.Marg, Gangtok",contactNo:"9475384683"},
  {hotelName:"M/S Garuda Hotel",placeName:"CHUNTHANG",address:"M.G.Marg, Gangtok",contactNo:"9475384683"},
  {hotelName:"Golden Heights",placeName:"CHUNTHANG",address:"Raj Gram Baichung Road Namchi South Sikkim",contactNo:"9475384683"},
  {hotelName:"M/S Green Valley",placeName:"JORETHANG",address:"Upper Balwakhani Below S.I.B. Office, Gangtok, East Sikkim",contactNo:"9475384683"},
  {hotelName:"Lotus Lodge",placeName:"DZONGU",address:"M.G.Marg, Gangtok",contactNo:"9832669390"},
  {hotelName:"Grand",placeName:"DZONGU",address:"Raj Gram Baichung Road Namchi South Sikkim",contactNo:"9832669390"},
  {hotelName:"Pang Seb",placeName:"NAMCHI",address:"Raj Gram Baichung Road Namchi South Sikkim",contactNo:"9832669390"},
  {hotelName:"Woodland",placeName:"ARITAR",address:"M.G.Marg, Gangtok",contactNo:"9832669390"},
  {hotelName:"Anugraha Hotel",placeName:"NAMCHI",address:"Deorali School Road",contactNo:"9475384683"},
  {hotelName:"Golden Pagoda",placeName:"NAMCHI",address:"M.G.Marg, Gangtok",contactNo:"9475384683"},
  {hotelName:"M/S Garuda Hotel",placeName:"RAVANGLA",address:"M.G.Marg, Gangtok",contactNo:"9475384683"},
  {hotelName:"Golden Heights",placeName:"RAVANGLA",address:"Raj Gram Baichung Road Namchi South Sikkim",contactNo:"9475384683"},
  {hotelName:"M/S Green Valley",placeName:"JORETHANG",address:"Upper Balwakhani Below S.I.B. Office, Gangtok, East Sikkim",contactNo:"9475384683"},
  {hotelName:"Lotus Lodge",placeName:"JORETHANG",address:"M.G.Marg, Gangtok",contactNo:"9832669390"},
  {hotelName:"Grand",placeName:"GANGTOK",address:"Raj Gram Baichung Road Namchi South Sikkim",contactNo:"9832669390"},
  {hotelName:"Pang Seb",placeName:"GANGTOK",address:"M.G.Marg, Gangtok",contactNo:"9832669390"},
  {hotelName:"Woodland",placeName:"VARSEY",address:"",contactNo:"9832669390"},
  {hotelName:"Anugraha Hotel",placeName:"VARSEY",address:"Deorali School Road",contactNo:"9475384683"},
  {hotelName:"Golden Pagoda",placeName:"ARITAR",address:"M.G.Marg, Gangtok",contactNo:"9475384683"},
  {hotelName:"M/S Garuda Hotel",placeName:"ARITAR",address:"M.G.Marg, Gangtok",contactNo:"9475384683"},
  {hotelName:"Golden Heights",placeName:"SORENG",address:"Raj Gram Baichung Road Namchi South Sikkim",contactNo:"9475384683"},
  {hotelName:"M/S Green Valley",placeName:"RUMTEK",address:"Upper Balwakhani Below S.I.B. Office, Gangtok, East Sikkim",contactNo:"9475384683"},
  {hotelName:"Lotus Lodge",placeName:"SORENG",address:"Raj Gram Baichung Road Namchi South Sikkim",contactNo:"9832669390"},
  {hotelName:"Grand",placeName:"VARSEY",address:"M.G.Marg, Gangtok",contactNo:"9832669390"},
  {hotelName:"Pang Seb",placeName:"VARSEY",address:"Raj Gram Baichung Road Namchi South Sikkim",contactNo:"9832669390"},
  {hotelName:"Woodland",placeName:"VARSEY",address:"Raj Gram Baichung Road Namchi South Sikkim",contactNo:"9832669390"} ]
this.app = this.app || {}
this.app.data = {places:data,gallery:gallerydata,hotels:hotels}